pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'devkit-api'

include 'devkit-core'
include 'devkit-registry'
include 'devkit-networking'
include 'devkit-components'
include 'devkit-config'
include 'devkit-datagen'
include 'devkit-client'
include 'devkit-fabric'
include 'devkit-testmod-example'
