org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.3
loom_version=1.17.17
fabric_version=0.136.1+1.21.8

mod_version=0.2.0-alpha.2+1.21.8
maven_group=io.github.jrxmod.devkit
archives_base_name=devkit-api
mod_author=jrxmod
devkit_api_version=2
